name: Discussion
description: Start a discussion about OpenTelemetry developer experience
title: "[Discussion] "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a discussion about OpenTelemetry developer experience!
        
        This template is for general discussions, questions, and ideas related to improving the developer experience.
  
  - type: textarea
    id: topic
    attributes:
      label: Discussion Topic
      description: What would you like to discuss?
      placeholder: I'd like to discuss...
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Background and Context
      description: Please provide any relevant background or context for this discussion.
      placeholder: This is relevant because...
    validations:
      required: false
  
  - type: dropdown
    id: area
    attributes:
      label: Area of Interest
      description: Which area of developer experience does this discussion relate to?
      multiple: true
      options:
        - Documentation
        - Tooling
        - API Design
        - SDK Usage
        - Getting Started Experience
        - Instrumentation
        - Debugging
        - Performance
        - Testing
        - Community
        - Other
    validations:
      required: false
  
  - type: textarea
    id: questions
    attributes:
      label: Questions to Consider
      description: Are there specific questions you'd like the community to consider?
      placeholder: |
        - How do we...?
        - What should we do about...?
        - Should we consider...?
    validations:
      required: false
  
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, links, or relevant information.
      placeholder: Additional details...
    validations:
      required: false
  
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
    default: 0